### ISSUE TITLE
Issues when used in conjunctions with CMake

### ISSUE THREAD

**Issue by Macr0Nerd** [Viatorus/quom#27]
I have a [C++ project](https://github.com/Macr0Nerd/eztplib) that uses CMake. The paths are provided by CMake, meaning they aren't wholly relative. This causes quom to not work with this. Is there a way to specify a source directory to always look for files in? All of my files are organized in a tree structure so that if I could specify "look from x directory" quom would find everything it needs.

**Comment by Viatorus** [comment]
This is currently not possible. But I will take a look this or next week how this could be done. :) Thank you for your interest!

**Comment by Macr0Nerd** [comment]
Alright thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Viatorus** [comment]
So, it should work now in version 1.2.0.

I also tested it with your project. Just run:

```quom include/eztp/eztp.hpp eztp.hpp -I include/```

Have a look here: https://gcc.godbolt.org/z/gp33ak

**Comment by Macr0Nerd** [comment]
Thank you so much!
