### ISSUE TITLE
Feature Request - List of symbols to export

### ISSUE THREAD

**Issue by jprjr** [Viatorus/quom#32]
My use-case, I have an older library that I need to keep for backwards compatibility. It has some symbols that conflict with other parts of the codebase, and I really just need a handful of functions from it. I currently use some compiler-specific flags to rename symbols.

The ask is if this could make everything `static`, except for a list of symbols (or something that does the inverse - takes a list of symbols and makes them `static`)

**Comment by Viatorus** [comment]
I understand you use case, but...

Quom has only a lexer (named tokenizer by me, which is not totally correct) so it identifies number, quotes, comments, whitespaces and others (names and symbols [+-/{}...]).

For your use case, a parser would be necessary to identify the syntax. Which is in C++ a non trivial task.

So this would be out-of-scope for this project. Sorry.

**Comment by jprjr** [comment]
OK - I totally understand, thank you for the response
