### ISSUE TITLE
quom command not found

### ISSUE THREAD

**Issue by raoufkh** [Viatorus/quom#39]
Hello,

I've installed quom using pip3 but when I try to run the command I've:
```
Command 'quom' not found, did you mean:

  command 'quot' from deb quota

Try: apt install <deb name>
```
Python3 and pip3 versions:
```
python3 --version
Python 3.6.9
pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```

**Comment by Viatorus** [comment]
Hello,

how did you install quom?

Is `quom

**Comment by raoufkh** [comment]
Hello Viatorus!

I think I had a problem with pip. I've been able to install it on another machine. Thank you!

**Comment by Viatorus** [comment]
Great!
