### ISSUE TITLE
option to skip already included files

### ISSUE THREAD

**Issue by hanickadot** [Viatorus/quom#42]
Hello and thanks for creating such awesome utility! I'm using it in my [CTRE](https://github.com/hanickadot/compile-time-regular-expressions) project. I noticed sometimes quom include same file multiple times. 

Would be possible to add an option to ignore already included files? Based on normalised URL preferably. 

Thanks! ❤️

**Comment by Viatorus** [comment]
Hello Hana, I know your project very well since I also did some compile time parsing attempts based on your research. Thank you.  I was happy to see, that you are using quom. ;)

In fact, multiple inclusion shouldn't happen. I will look into this.

**Comment by hanickadot** [comment]
Seems the multiple inclusion happens if the include directive has different relative path, hope this will help. ❤️

**Comment by Viatorus** [comment]
Should be fixed in version [![image](https://user-images.githubusercontent.com/3637911/122113259-259a2100-ce22-11eb-838d-4476ffe88ee0.png)](https://pypi.org/project/quom/).

Thank you for using quom! :)

**Comment by hanickadot** [comment]
Thank you! :)
