### ISSUE TITLE
error while loading shared libraries: MSVCR120.dll: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ishandutta2007** [Viatorus/quom#50]
I am on MinGW x64 system hosted on Windows7
I installed `quom` via
```
pip install --user quom
PATH=/c/users/hp/.local/bin:$PATH
quom crt.hpp crt_gen.cpp
```

> C:/users/hp/.local/bin/quom.exe: error while loading shared libraries: MSVCR120.dll: cannot open shared object file: No such file or directory

My understanding is `MSVCR120.dll` comes with Microsoft Visual studio . If anything more needs to be installed for `quom` that should go into documentations.

There is no issue with the usual way of running this which is like this:
```
$ g++ crt.cpp -o crt.exe -L/mingw64/bin -I/mingw64/include/flint -lgmp -lflint -lpthread
$ ./crt 2342
```

> Everything is Fine

**Comment by ishandutta2007** [comment]
I solved `MSVCR120.dll` issue following https://youtu.be/3_dQI16sA5g
but `quom crt.cpp crt_gen.cpp` is still not generating any new file.

**Comment by ishandutta2007** [comment]
Since the issue under title is resolved, currently the issue is different. So closing this ticket in lieu of https://github.com/Viatorus/quom/issues/51

**Comment by Viatorus** [comment]
> My understanding is MSVCR120.dll comes with Microsoft Visual studio . If anything more needs to be installed for quom that should go into documentations.

Quom needs a working Python 3.7 runtime. Nothing more.
